language: node_js
node_js:  
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
sudo: false

service:
    - imagick

script: "make test-travis"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
